services:
  - type: web
    name: dailydo-backend
    runtime: docker
    repo: https://github.com/Saad-Kamran-2006/dailyDo-Todo-App # You might need to change this if your repo structure is different or private
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false # User needs to input this manually in Render dashboard
    dockerContext: . # directory containing Dockerfile
